Repository microsoft/CsWinRT, pull requests merged in 2024-04, with the labels that each got.

#1561 Use MethodInvoker in MarshalGenericFallback<T>
  src/WinRT.Runtime/Marshalers.cs
Labels: performance, gc

#1555 Add RcwReflectionFallbackGenerator type
  build/AzurePipelineTemplates/CsWinRT-Variables.yml
  nuget/Microsoft.Windows.CsWinRT.targets
  nuget/readme.md
  src/Authoring/WinRT.SourceGenerator/Helper.cs
  src/Authoring/WinRT.SourceGenerator/RcwReflectionFallbackGenerator.cs
Labels: trimming

#1565 Add 'CsWinRTEnableICustomPropertyProviderSupport' feature switch
  nuget/Microsoft.Windows.CsWinRT.targets
  src/WinRT.Runtime/ComWrappersSupport.cs
  src/WinRT.Runtime/Configuration/FeatureSwitches.cs
  src/WinRT.Runtime/Configuration/ILLink.Substitutions.xml
  src/WinRT.Runtime/Projections/ICustomPropertyProvider.net5.cs
Labels: trimming

#1568 Fix an incorrect IL3050 warning suppression for ILC
  src/WinRT.Runtime/IWinRTObject.net5.cs
Labels: AOT

#1575 Add 'CsWinRTEnableIReferenceSupport' feature switch
  nuget/Microsoft.Windows.CsWinRT.targets
  src/WinRT.Runtime/ComWrappersSupport.cs
  src/WinRT.Runtime/Configuration/FeatureSwitches.cs
  src/WinRT.Runtime/Configuration/ILLink.Substitutions.xml
  src/WinRT.Runtime/Projections/EventHandler.cs
  src/WinRT.Runtime/Projections/Nullable.cs
  src/WinRT.Runtime/TypeExtensions.cs
  src/WinRT.Runtime/TypeNameSupport.cs
Labels: trimming

#1431 Disable runtime marshalling for the CsWinRT repo.
  src/Authoring/Directory.Build.props
  src/Projections/Directory.Build.props
  src/WinRT.Runtime/Directory.Build.props
Labels: performance, AOT

#1586 Don't cache 'RegisterTypeRuntimeClassNameLookup'
  src/Authoring/WinRT.SourceGenerator/AotOptimizer.cs
Labels: trimming

#1583 Add 'CsWinRTEnableIDynamicInterfaceCastableSupport' feature switch
  nuget/Microsoft.Windows.CsWinRT.targets
  nuget/readme.md
  src/WinRT.Runtime/Configuration/FeatureSwitches.cs
  src/WinRT.Runtime/Configuration/ILLink.Substitutions.xml
  src/WinRT.Runtime/IWinRTObject.net5.cs
  src/WinRT.Runtime/ObjectReference.cs
  src/WinRT.Runtime/Projections/IDictionary.net5.cs
  src/WinRT.Runtime/Projections/INotifyDataErrorInfo.net5.cs
  src/WinRT.Runtime/SingleInterfaceOptimizedObject.net5.cs
  src/WinRT.Runtime/TypeNameSupport.cs
Labels: trimming

#1589 Remove even more closure allocations in ObjectReferenceWithContext<T>
  src/WinRT.Runtime/Context.cs
  src/WinRT.Runtime/Interop/IContextCallback.cs
  src/WinRT.Runtime/ObjectReference.cs
Labels: performance, gc

#1588 Remove more closures in lambda expressions
  src/WinRT.Runtime/ComWrappersSupport.cs
  src/WinRT.Runtime/ComWrappersSupport.net5.cs
  src/WinRT.Runtime/ComWrappersSupport.netstandard2.0.cs
  src/WinRT.Runtime/IWinRTObject.net5.cs
  src/WinRT.Runtime/MatchingRefApiCompatBaseline.txt
  src/WinRT.Runtime/Projections/Bindable.net5.cs
  src/WinRT.Runtime/Projections/CollectionHybrid.net5.cs
Labels: performance, gc

#1577 Fix IL2087 trim warning in 'ObjectReferenceWithContext<T>'
  src/WinRT.Runtime/ActivationFactory.cs
  src/WinRT.Runtime/AgileReference.cs
  src/WinRT.Runtime/ComWrappersSupport.cs
  src/WinRT.Runtime/ComWrappersSupport.net5.cs
  src/WinRT.Runtime/Context.cs
  src/WinRT.Runtime/IInspectable.cs
  src/WinRT.Runtime/Interop/ExceptionErrorInfo.net5.cs
  src/WinRT.Runtime/Interop/IActivationFactory.cs
  src/WinRT.Runtime/Interop/IAgileReference.net5.cs
  src/WinRT.Runtime/Interop/IContextCallback.cs
  src/WinRT.Runtime/Interop/IID.g.cs
  src/WinRT.Runtime/Interop/IID.tt
  src/WinRT.Runtime/Interop/IMarshal.cs
  src/WinRT.Runtime/MatchingRefApiCompatBaseline.txt
  src/WinRT.Runtime/ObjectReference.cs
  src/WinRT.Runtime/Projections/Bindable.net5.cs
  src/WinRT.Runtime/Projections/DataErrorsChangedEventArgs.cs
  src/WinRT.Runtime/Projections/ICommand.net5.cs
  src/WinRT.Runtime/Projections/IDictionary.net5.cs
  src/WinRT.Runtime/Projections/IEnumerable.net5.cs
  src/WinRT.Runtime/Projections/IList.net5.cs
  src/WinRT.Runtime/Projections/INotifyCollectionChanged.net5.cs
  src/WinRT.Runtime/Projections/INotifyDataErrorInfo.net5.cs
  src/WinRT.Runtime/Projections/INotifyPropertyChanged.net5.cs
  src/WinRT.Runtime/Projections/IReadOnlyDictionary.net5.cs
  src/WinRT.Runtime/Projections/IReadOnlyList.net5.cs
  src/WinRT.Runtime/Projections/IReferenceArray.net5.cs
  src/WinRT.Runtime/Projections/KeyValuePair.cs
  src/WinRT.Runtime/Projections/NotifyCollectionChangedEventArgs.cs
  src/WinRT.Runtime/Projections/Nullable.cs
  src/WinRT.Runtime/Projections/PropertyChangedEventArgs.cs
  src/WinRT.Runtime/Projections/Uri.cs
  src/cswinrt/code_writers.h
  src/cswinrt/strings/additions/Windows.Storage.Streams/IMarshal.cs
Labels: trimming

#1594 Pass more explicit IIDs in more places
  src/WinRT.Runtime/CastExtensions.cs
  src/WinRT.Runtime/IInspectable.cs
  src/WinRT.Runtime/Interop/IActivationFactory.cs
  src/WinRT.Runtime/Interop/IAgileReference.net5.cs
  src/WinRT.Runtime/Projections/DataErrorsChangedEventArgs.cs
  src/WinRT.Runtime/Projections/PropertyChangedEventArgs.cs
  src/WinRT.Runtime/Projections/Uri.cs
Labels: performance, trimming

#1592 Set 'TreatWarningsAsErrors' almost everywhere
  src/Authoring/Directory.Build.props
  src/Authoring/WinRT.SourceGenerator/DiagnosticUtils.cs
  src/Authoring/WinRT.SourceGenerator/Generator.cs
  src/Authoring/WinRT.SourceGenerator/Helper.cs
  src/Authoring/WinRT.SourceGenerator/ImmutableEquatableArray.cs
  src/Authoring/WinRT.SourceGenerator/Logger.cs
  src/Authoring/WinRT.SourceGenerator/WinRT.SourceGenerator.csproj
  src/Authoring/WinRT.SourceGenerator/WinRTTypeWriter.cs
  src/Authoring/cswinmd/CsWinMD.csproj
  src/Authoring/cswinmd/Program.cs
  src/Projections/Directory.Build.props
  src/Projections/Test/TestHost.ProbeByHost.cs
  src/Projections/TestHost.ProbeByClass/TestHost.ProbeByClass.cs
  src/Tests/AuthoringTest/AuthoringTest.csproj
  src/Tests/AuthoringTest/Directory.Build.props
  src/Tests/FunctionalTests/Directory.Build.props
  src/WinRT.Runtime/ApiCompatBaseline.txt
  src/WinRT.Runtime/ComWrappersSupport.cs
  src/WinRT.Runtime/Directory.Build.props
  src/WinRT.Runtime/MatchingRefApiCompatBaseline.txt
  src/WinRT.Runtime/Projections.cs
  src/WinRT.Runtime/Projections/Nullable.cs
  src/WinRT.Runtime/Projections/Type.cs
  src/WinRT.Runtime/TypeExtensions.cs
  src/WinRT.Runtime/TypeNameSupport.cs
  src/WinRT.Runtime/WinRT.Runtime.csproj
  src/cswinrt/strings/additions/Windows.Storage.Streams/WindowsRuntimeBuffer.cs
  src/cswinrt/strings/additions/Windows.Storage.Streams/WindowsRuntimeStreamExtensions.cs
Labels: validation

#1591 Seal and tweak 'IWinRTObject' members
  src/WinRT.Runtime/ApiCompatBaseline.txt
  src/WinRT.Runtime/IWinRTObject.net5.cs
  src/WinRT.Runtime/SingleInterfaceOptimizedObject.net5.cs
Labels: performance, breaking change

#1567 Add 'CsWinRTRcwFactoryFallbackGeneratorForceOptOut' property
  nuget/Microsoft.Windows.CsWinRT.targets
  nuget/readme.md
  src/Authoring/WinRT.SourceGenerator/Helper.cs
  src/Authoring/WinRT.SourceGenerator/RcwReflectionFallbackGenerator.cs
Labels: trimming

#1596 Pass IID for 'IBufferByteAccess.FromAbi'
  src/WinRT.Runtime/Interop/IID.g.cs
  src/WinRT.Runtime/Interop/IID.tt
  src/cswinrt/strings/additions/Windows.Storage.Streams/IBufferByteAccess.cs
  src/cswinrt/strings/additions/Windows.Storage.Streams/WindowsRuntimeBuffer.cs
Labels: trimming, AOT
